PLENTY-300 install php codesniffer
findologic/plugin-plentymarkets-ceres-api pull request #246
Opened 2021-03-10 14:19 UTC by RimantasAdeoWeb

2021-03-10 15:13 UTC, TheKeymaster requested changes

2021-03-10 15:13 UTC, TheKeymaster commented on src/Services/SearchService.php
> -    CONST DEFAULT_ITEMS_PER_PAGE = 25;
Can't believe that PHP actually allows this :see_no_evil:

2021-03-10 15:13 UTC, TheKeymaster commented on tests/Services/Search/ParametersHandlerTest.php
> +        return $config = (object) [
This is some hacky code right there. Can we use `stdClass` instead here?

2021-03-10 15:13 UTC, TheKeymaster commented on .travis.yml
> +  - composer test
Please add a newline at the end here.

2021-03-15 09:10 UTC, RimantasAdeoWeb commented
Sorry, had to force-push. Messed the branch up a bit on thursday trying to figure out why it wouldn't build (turned out not to be related to this after all)

2021-03-15 10:15 UTC, TheKeymaster approved these changes

2021-03-15 11:21 UTC, merged