Plenty 458 price filter range
findologic/plugin-plentymarkets-ceres-api pull request #350
Opened 2022-12-12 13:00 UTC by Mariusslo

2023-01-05 11:45 UTC, TobiasGraml11 requested changes

2023-01-05 11:45 UTC, TobiasGraml11 commented on resources/js/src/app/components/itemList/filter/ItemRangeSlider.vue
> +      }
How about setting the configuration value already to the correct number?
So use the current caption as value as well.

2023-01-05 11:45 UTC, TobiasGraml11 commented on resources/lang/de/Config.properties
> +priceRangeFilterSteps=Dezimalpunkte im Preisbereichsfilter
"No newline at end of file"

2023-01-05 11:45 UTC, TobiasGraml11 commented on resources/lang/en/Config.properties
> +priceRangeFilterSteps=Decimal points in price range filter
"No newline at end of file"

2023-01-05 11:45 UTC, TobiasGraml11 commented on src/Api/Response/Parser/FiltersParser.php
> +{
```suggestion
{
```

2023-01-05 11:45 UTC, TobiasGraml11 commented on src/Api/Response/Parser/FiltersParser.php
> +        if ($filterName === 'price' && $filterData['findologicFilterType'] === Plugin::FILTER_TYPE_RANGE_SLIDER) {
Let's use this configuration for all range sliders.

```suggestion
        if ($filterData['findologicFilterType'] === Plugin::FILTER_TYPE_RANGE_SLIDER) {
```

2023-01-05 11:45 UTC, TobiasGraml11 commented on tests/Api/Response/Parser/FiltersParserTest.php
> +
```suggestion

```

2023-01-05 11:45 UTC, TobiasGraml11 commented on resources/lang/de/Config.properties
> +priceRangeFilterSteps=Dezimalpunkte im Preisbereichsfilter
```suggestion
priceRangeFilterSteps=Dezimalstellen für Bereichsfilter
```

2023-01-05 11:45 UTC, TobiasGraml11 commented on resources/lang/en/Config.properties
> +priceRangeFilterSteps=Decimal points in price range filter
```suggestion
priceRangeFilterSteps=Decimal places for range sliders
```

2023-01-05 12:09 UTC, Mariusslo commented on resources/js/src/app/components/itemList/filter/ItemRangeSlider.vue
> +      }
Then we don't have the correct step variable to pass, as we need to configure values:
- for the step count (stepSize)
- for the decimals for formating

2023-01-05 12:12 UTC, TobiasGraml11 commented on resources/js/src/app/components/itemList/filter/ItemRangeSlider.vue
> +      }
Makes sense, thanks.

Then please use https://www.php.net/manual/de/control-structures.match.php instead of the if blocks.

2023-01-05 12:13 UTC, TobiasGraml11 commented on resources/js/src/app/components/itemList/filter/ItemRangeSlider.vue
> +      }
True, thanks!

2023-01-09 08:19 UTC, TobiasGraml11 requested changes

2023-01-09 08:19 UTC, TobiasGraml11 commented on package.json
> +    "run": "^1.4.0",
Why was this added now?

2023-01-09 08:19 UTC, TobiasGraml11 commented on tests/Api/Response/Parser/FiltersParserTest.php
> +                'configRepository' => $this->configRepository
Just noticed, that we do not test if the configuration is set correctly. Could you add a test for that?

2023-01-10 14:17 UTC, TobiasGraml11 approved these changes

2023-01-10 14:44 UTC, merged