Ph 1083 empty search request
findologic/plugin-plentymarkets-ceres-api pull request #387
Opened 2024-08-16 12:27 UTC by rimvydas-hashtages

2024-08-16 12:32 UTC, rimvydas-hashtages commented
@simonhintersonnleitner build seems failing because it cant pull plenty-ceres repo `Error: Failed to clone https://github.com/plentymarkets/plugin-ceres via https, ssh protocols, aborting.` Maybe we should try upping the plenty lts version

2024-08-16 23:44 UTC, Bibarella commented
> @simonhintersonnleitner build seems failing because it cant pull plenty-ceres repo `Error: Failed to clone https://github.com/plentymarkets/plugin-ceres via https, ssh protocols, aborting.` Maybe we should try upping the plenty lts version

Ran it again and it worked

2024-08-16 23:51 UTC, Bibarella requested changes

2024-08-16 23:51 UTC, Bibarella commented on resources/js/src/app/shared/UrlBuilder.ts
> +        const map = {
Extend map to handle additional characters, such as > (&gt;) and & (&amp;) please

2024-08-23 12:00 UTC, simonhintersonnleitner reviewed
⚙️  Please keep in this MR just the changes the needed for the fix. It' looks like that there are change from the other [MR](https://github.com/findologic/plugin-plentymarkets-ceres-api/pull/386).

2024-08-26 11:14 UTC, closed without merging